steps:
- name: 'maven'
  script: 'mvn  versions:set -DnewVersion=1'
  dir: spring-boot-app
  # args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1', '.' ]
